# version format
version: 2.00.{build}-{branch}
 
# branches to build
branches:
  # blacklist
  except:
    - gh-pages
skip_tags: true
 
# Operating system (build VM template)
os: Visual Studio 2015
init:
  - git config --global core.longpaths true

clone_folder: c:\boost.afio
platform: x64 
configuration: Release

before_build:
  - git checkout master
  - git submodule update --init --recursive
  - mkdir build
build_script:
  - cd build
  - cmake ..
  - cmake --build . --config Release
after_build:
  - cd ..
  - dir build\bin\Release
  - dir build\lib\Release
  - 7z a afio_v2_binaries_win64.zip doc include Readme.md release_notes.md build\bin\Release\afio_dl-2.0-Windows-Win32-Release.dll lib\Release\afio_sl-2.0-Windows-Win32-Release.lib

before_test:
  - cd build
test_script:
  - ctest -D Experimental -C Release
after_test:
  - copy bin\Release\*.xml results.xml

on_success:
on_failure:
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\results.xml))

artifacts:
  - path: afio_v2_binaries_win64.zip
