# version format
version: 2.00.{build}-{branch}
 
# branches to build
branches:
  # blacklist
  except:
    - gh-pages
skip_tags: true
 
# Operating system (build VM template)
os: Visual Studio 2015
init:
  - git config --global core.longpaths true

clone_folder: c:\boost.afio
platform: x64 
configuration: Release
environment:
  JENKINS_NEDPROD_PASSWORD:
    secure: vI+U4YDxi99hN90v6LMvmg==

before_build:
  - git checkout master
  - git submodule update --init --recursive
build_script:
  - ctest -S .ci.cmake -V
after_build:
  - for /f %%a in ('powershell -Command "Get-Date -format yyyyMMddHHmm"') do set datetime=%%a
  - set "TARNAME=boost.afio-v2.0-binaries-win64-%datetime%.zip"
  - 7z a %TARNAME% doc include Readme.md release_notes.md build\bin\Release\afio_dl-2.0-Windows-x64-Release.dll build\lib\Release\afio_dl-2.0-Windows-x64-Release.lib build\lib\Release\afio_sl-2.0-Windows-x64-Release.lib

before_test:
test_script:
after_test:

on_success:
  - curl -u jenkins-nedprod:%JENKINS_NEDPROD_PASSWORD% --data-binary @%TARNAME% https://dedi4.nedprod.com/static/files/upload/%TARNAME%
on_failure:
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path build\merged_junit_results.xml))

#artifacts:
