# version format
version: 2.00.{build}-{branch}
 
# branches to build
branches:
  # blacklist
  except:
    - gh-pages
skip_tags: true
 
image: Visual Studio 2017
init:
  - git config --global core.longpaths true

clone_folder: c:\boost.afio
platform: x64 
configuration: Release
environment:
  JENKINS_NEDPROD_PASSWORD:
    secure: 9Bx/dfr0ne9DTgnezRILRuOrPOZ71pVuzWBAscR9vTG9n42gIvNhYVCaCnr6FMa/

before_build:
  - git checkout master
  - git submodule update --init --recursive
build_script:
  - ctest -S .ci.cmake -V --timeout 300
after_build:

before_test:
test_script:
after_test:

on_success:
on_failure:
on_finish:
  - dir prebuilt\bin\Release
  - dir prebuilt\lib\Release
  - echo %date%
  - set "NEWNAME=afio-v2.0-binaries-win64-%date:~10,4%%date:~7,2%%date:~4,2%%time:~0,2%%time:~3,2%.tar.gz"
  - echo %NEWNAME%
  - rename afio-v2.0-binaries-win64.tar.gz "%NEWNAME"
  - curl -T "%NEWNAME%" -u jenkins-nedprod:%JENKINS_NEDPROD_PASSWORD% https://dedi4.nedprod.com/static/files/upload/
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path prebuilt\merged_junit_results.xml))
