# version format
version: 2.00.{build}-{branch}
 
# branches to build
branches:
  # blacklist
  except:
    - gh-pages
skip_tags: true
 
image: Visual Studio 2017
init:
  - git config --global core.longpaths true

clone_folder: c:\boost.afio
platform: x64 
configuration: Release
environment:
  JENKINS_NEDPROD_PASSWORD:
    secure: u6OVf3jbCA7VXY6L+KztW2Isw4pcWLSDfkqJfv+IsikJrgjQS08Yb6Wdp6CY4vk8

before_build:
  - git checkout master
  - git submodule update --init --recursive
build_script:
  - ctest -S .ci.cmake -V --timeout 300
after_build:

before_test:
test_script:
after_test:

on_success:
on_failure:
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path prebuilt\merged_junit_results.xml))
